Proxy/implementation
azerpas/fractif-asset-token pull request #16
Opened 2022-09-15 14:48 UTC by Tixwell

I just finish the deploy proxy and a test to upgrade it, I will wrote the deploy-proxy / upgrade-proxy script once you finish change into hardhat 

cc @azerpas

2022-09-16 13:53 UTC, azerpas requested changes
Nice, can you review the changes with IERC20Upgradable? Otherwise it should be good!

2022-09-16 13:53 UTC, azerpas commented on .env.example
> +alchemy_goerli_url=....
In UPPERCASE bro

2022-09-16 13:53 UTC, azerpas commented on README.md
>  - Run in shell
nice

2022-09-16 13:53 UTC, azerpas commented on contracts/FractifV1.sol
> +            IERC20Upgradeable(depositedCoin).transferFrom(
This shouldn't get converted to `IERC20Upgradeable` as we're only using IERC to transfer tokens from the smart-contract balance to users, but these tokens on their own we don't know if they're upgradable. 

**same goes for the same changes below 1️⃣**

2022-09-16 13:53 UTC, azerpas commented on contracts/FractifV1.sol
> +            uint256 balance = IERC20Upgradeable(tokenDepositedCoin[tokenId]).balanceOf(
1️⃣

2022-09-16 13:53 UTC, azerpas commented on contracts/FractifV1.sol
> +                IERC20Upgradeable(tokenDepositedCoin[tokenId]).transfer(
1️⃣

2022-09-17 09:42 UTC, Tixwell commented
@azerpas tell me if those change are good for you and tell me when I can merge it!

2022-09-18 12:54 UTC, azerpas approved these changes
LGTM :)

2022-09-18 12:55 UTC, merged